Description: Template for creating EC2 instance

Parameters:
  EC2InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  EC2InstanceAmiId:
    Description: AMI identifier for the EC2 instance
    Type: String
    Default: ami-0cf6f5c8a62fa5da6

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 'my-key-pair'
      ImageId: !Ref EC2InstanceAmiId
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  PublicIp:
    Description: EC2 Instance public IP
    Value: !GetAtt EC2Instance.PublicIp